Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtTokenDTO.swift

- JwtTokenDTO를 API 명세서의 필드로 받을 수 있게 바꿉니다

🔀 :: JwtTokenDTO API 명세서와 일치화

---

Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift

SMSIcon을 사용할 때 생성자에서 renderingMode를 받습니다.
SMSIcon 생성자에 renderingMode 추가
SMSIcon 생성자에 renderingMode 추가
```swift
SMSIcon(.camera, renderingMode: .original)
```

🔀 :: SMSIcon의 renderingMode를 생성자로 받도록 변경

---

Projects/Core/DesignSystem/Sources/Chip/SMSChip.swift
Projects/Core/DesignSystem/Sources/Chip/SMSChipButtonStyle.swift

디자인 시스템의 Chip 컴포넌트를 구현합니당
https://github.com/GSM-MSG/SMS-iOS/assets/74440939/009c9e36-9578-4fc1-8fd7-7ca3a32a590a
디자인 시스템의 Chip 컴포넌트 제작
```swift
SMSChip("ASDAF")
SMSChip("asdasd") {
SMSLogger.info("ㄹㅇㅋㅋ")
} iconLabel: {
SMSIcon(.camera)
}
```

🔀 :: Design System - Chip 제작

---

Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
Projects/Core/DesignSystem/Sources/Extension/View+smsBackButton.swift

전체 화면에서 공통적으로 사용할 backButton modifier를 추가합니다
https://github.com/GSM-MSG/SMS-iOS/assets/74440939/460a06be-147a-4e8b-9cfa-6d99b0f1891e
```swift
...
.smsBackButton(dismiss: dismiss: willDismiss: { })

🔀 :: smsBackButton modifier 추가

---

Scripts/CodeSigning.swift
Scripts/GenerateModule.swift
Scripts/InitEnvironment.swift
Scripts/NewDependency.swift

🔀 :: Script에 signal 감지로 취소 감지

---

Projects/Core/DesignSystem/Sources/Extension/View+smsBackButton.swift

View+smsBackButton와 View+interactivePop 파일에서 동시에 delegate를 위임해서 생긴 문제를 해결합니다

🔀 :: Navigation Delegate 중복 제거

---

Projects/Core/DesignSystem/Sources/CameraPicker/CameraPicker.swift
Projects/Core/DesignSystem/Sources/ImagePicker/MiltipleImagePicker.swift
Projects/Core/DesignSystem/Sources/ImagePicker/PickedImage.swift
Projects/Core/DesignSystem/Sources/ImagePicker/SingleImagePicker.swift

<div>
</div>
- SingleImagePicker
- MultipleImagePicker
- CameraPicker
```swift
// Single ImagePicker
VStack{}
.imagePicker(isShow: $isShowing, pickedImageResult: $pickedImageResult)
.imagePicker(isShow: $isShowing, pickedImageResult: $pickedImageResult, filter: .images)
// MultipleImagePicker
VStack{}
.imagePicker(isShow: $isShowing, pickedImageResult: $pickedImageResult)
.imagePicker(isShow: $isShowing, pickedImageResult: $pickedImageResult, filter: .images)
.imagePicker(isShow: $isShowing, pickedImageResult: $pickedImageResult, filter: .images, limit: 3)
// CameraPicker
VStack{}
.cameraPicker(isShow: $isShowing, pickedImageResult: $pickedImageResult)

🔀 :: 이미지 & 카메라 Picker

---

Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift

프로필 정보를 입력할 때 타이틀이 '학교 생활' 인 오타를 수정
프로필 정보를 입력할 때 타이틀이 '학교 생활' 인 오타를 '프로필'로 수정

🔀 :: 정보 입력 - 프로필 정보 입력 페이지의 타이틀 오타

---

Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift

프로필 정보 입력 페이지 분야 선택 Placeholder 변경

 🔀 :: 프로필 정보 입력 페이지 분야 선택 Placeholder 변경

---

Projects/Domain/StudentDomain/Interface/Enums/FormOfEmployment.swift
Projects/Domain/StudentDomain/Interface/Enums/MilitaryService.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Intent/InputSchoolLifeInfoIntent.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModel.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModelProtocol.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Scene/InputSchoolLifeInfoView.swift
Projects/Feature/InputSchoolLifeInfoFeature/Tests/InputSchoolLifeInfoFeatureTest.swift
Projects/Feature/InputWorkInfoFeature/Interface/InputWorkDelegate.swift
Projects/Feature/InputWorkInfoFeature/Project.swift
Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntentProtocol.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModelProtocol.swift
Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift

근무 조건을 입력하는 페이지에서 validation및 일부 사용성 개선 + InputInformation에 정보를 전달합니다.
- 희망 연봉 입력할 때 TextField 아래에 00만원 환전 시켜 표시
- 입력 완료 시 InputInformation에 정보 전달
- 각 Enum에 Encodable을 Codable로 변경
- 각 Enum에 CaseIterable 컨펌

🔀 :: 정보 입력 - 근무 조건 페이지 정보 검사 및 입력 전달

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/InputCertificateInfoFeature/Interface/InputCertificateDelegate.swift
Projects/Feature/InputCertificateInfoFeature/Sources/Intent/InputCertificateInfoIntent.swift
Projects/Feature/InputCertificateInfoFeature/Sources/Intent/InputCertificateInfoIntentProtocol.swift
Projects/Feature/InputCertificateInfoFeature/Sources/Scene/InputCertificateInfoView.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift

자격증 정보를 입력하는 페이지에서 입력 받은걸 검사하고 InputInformation에 전달합니다

🔀 :: 정보 입력 - 자격증 입력 검사 및 전달

---

Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModel.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModelProtocol.swift

필수 입력란 입력 안할 시 버튼의 상태를 Disabled시킵니다
- InputProfileState에 buttonDisabled 상태 추가
- InputSchoolLifeState에 buttonDisabled 상태 추가
- InputProfileView에 버튼 Disabled 상태 추가
- InputSchoolLifeView에 버튼 Disabled 상태 추가

🔀 :: 정보 입력 - 프로필, 학교 생활 정보 입력 버튼 Disabled 상태 추가

---

Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift

TextField의 에러가 활성화 될때 vmark의 위치가 이상해 지는 현상 해결
vmark 이미지의 overlay alignment를 trailing에서 topTrailing으로 변경. padding을 trailing에서 top, trailing으로 변경

🔀 :: TextField의 에러가 활성화 될때 vmark의 위치가 이상해 지는 현상 해결

---

Tuist/ProjectDescriptionHelpers/Action+Template.swift

SwiftLint를 RunScript로 돌릴 때 BasedOnDependency를 false로 해주지 않아 생긴 문제를 해결합니다.

🔀 :: SwiftLint RunScript에서 warning뜨는 현상 해결

---

Projects/Domain/AuthDomain/Interface/Error/AuthDomainError.swift
Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
Projects/Domain/AuthDomain/Testing/UseCase/LoginUseCaseSpy.swift
Projects/Domain/AuthDomain/Tests/Repository/AuthRepositorySpec.swift
Projects/Domain/AuthDomain/Tests/UseCase/LoginUseCaseSpec.swift

명세서에 맞게 400, 401, 404를 GAuth 로그인에서 실패한것으로 처리합니다.
- invalidGAuthCode 에러 -> failedToGAuthSignin 에러 로 이름 변경
- AuthEndpoint에서 400, 401, 404의 에러를 failedToGAuthSignin으로 설정

🔀 :: AuthDomainError를 API명세서와 동일하게 수정합니다

---

Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift

TextField에 텍스트 입력 시 xmark와 겹쳐지던 현상 해결

🔀 :: TextField에 텍스트 입력 시 xmark와 겹쳐지던 현상 해결

---

Projects/App/Support/Info.plist
Projects/Feature/SigninFeature/Sources/Scene/View/GAuthButtonView.swift

- REDIREDCT_URI로 되어있는 이름을 REDIRECT_URI로 변경
- GAuthButtonView에서 REDIREDCT_URI 를 Key로 환경 변수 가져오는 것을 REDIRECT_URI로 변경
- gauthButton prepare할 때 completion 부분 파라미터로 바로 넘기도록 수정
- gauthButton prepare할 때 completion 부분 파라미터로 바로 넘기도록 수정

🔀 :: GAuth 환경 변수 이름 오타 수정

---

Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtInterceptor.swift
Projects/Domain/MajorDomain/Sources/Endpoint/MajorEndpoint.swift
Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
Tuist/Dependencies.swift

JwtInterceptor에 Jwt 토큰 자동 담기 및 쿠키 제거
- JwtInterceptor에서 didRecive 작동 시 토큰 DTO 디코딩 여부 판단 후 JwtStore에 데이터 저장
- 데이터를 받을때마다 쿠키 제거

🔀 :: JwtInterceptor에 Jwt 토큰 자동 담기 및 쿠키 제거

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
Projects/Feature/RootFeature/Sources/Model/RootModel.swift
Projects/Feature/SigninFeature/Interface/SigninDelegate.swift
Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
Projects/Feature/SigninFeature/Sources/Intent/SigninIntentProtocol.swift
Projects/Feature/SigninFeature/Sources/Scene/SigninView.swift

GuestSignin 버튼 제작	
<img src="https://github.com/GSM-MSG/SMS-iOS/assets/81547954/a72795c6-bc67-4f39-a938-feae32cf6230" width="200">

🔀 :: GuestSignin 버튼 제작

---

Projects/Domain/StudentDomain/Interface/Error/StudentDomainError.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift

정보 입력 완료 후 요청을 실패할 시 유저에게 에러 메시지를 전달합니다.

🔀 :: 정보 입력 실패 시 유저에게 에러 메시지 전달

---

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
Projects/Core/DesignSystem/Project.swift
Projects/Core/DesignSystem/Sources/Loading/SMSLoading.swift
Projects/Core/DesignSystem/Sources/Lottie/LottieView.swift
Projects/Feature/SigninFeature/Sources/Scene/SigninView.swift
Tuist/Dependencies.swift
Tuist/ProjectDescriptionHelpers/Project+Template.swift
Tuist/ResourceSynthesizers/Lottie.stencil

🔀 :: 로그인 페이지 타이틀 폰트 정상화

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
Projects/Feature/MainFeature/Sources/Intent/MainIntentProtocol.swift
Projects/Feature/MainFeature/Sources/Model/MainModel.swift
Projects/Feature/MainFeature/Sources/Model/MainModelProtocol.swift
Projects/Feature/MainFeature/Sources/Scene/MainView.swift

메인 페이지 refresh 기능 추가
메인 페이지 refresh 기능 추가
* Refresh 만듬!
이거 통합 어떻게 시키는지 아시나요?

🔀 :: 메인 페이지 refresh 기능 추가

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Domain/BaseDomain/Sources/Base/SMSDomain.swift
Projects/Domain/UserDomain/Interface/DI/UserDomainBuildable.swift
Projects/Domain/UserDomain/Interface/DataSource/Remote/RemoteUserDataSource.swift
Projects/Domain/UserDomain/Interface/Entity/MyPageEntity.swift
Projects/Domain/UserDomain/Interface/Error/UserDomainError.swift
Projects/Domain/UserDomain/Interface/Repository/UserRepository.swift
Projects/Domain/UserDomain/Interface/UseCase/FetchMyMiniProfileUseCase.swift
Projects/Domain/UserDomain/Interface/UseCase/FetchMyProfileUseCase.swift
Projects/Domain/UserDomain/Project.swift
Projects/Domain/UserDomain/Sources/DI/UserDomainComponent.swift
Projects/Domain/UserDomain/Sources/DTO/Response/FetchMyMiniProfileResponseDTO.swift
Projects/Domain/UserDomain/Sources/DTO/Response/FetchMyProfileResponseDTO.swift
Projects/Domain/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
Projects/Domain/UserDomain/Sources/Endpoint/UserEndpoint.swift
Projects/Domain/UserDomain/Sources/Repository/UserRepositoryImpl.swift
Projects/Domain/UserDomain/Sources/UseCase/FetchMyMiniProfileUseCaseImpl.swift
Projects/Domain/UserDomain/Sources/UseCase/FetchMyProfileUseCaseImpl.swift
Projects/Feature/FilterFeature/Sources/Scene/FilterView.swift

마이페이지, 유저 프로필 관련한 API를 작업합니다
- FetchMyMiniProfileUseCase
- FetchMyProfileUseCase

🔀 :: 마이페이지 관련 API 작업

---

Projects/Domain/StudentDomain/Interface/Entity/PrizeEntity.swift
Projects/Domain/StudentDomain/Interface/Entity/ProjectEntity.swift
Projects/Domain/StudentDomain/Interface/Entity/StudentDetailEntity.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByGuestResponseDTO.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByStudentResponseDTO.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByTeacherResponseDTO.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/PrizeResponseDTO.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/ProjectResponseDTO.swift
Projects/Domain/StudentDomain/Testing/UseCase/FetchStudentUseCaseSpy.swift
Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift

- 학생의 자기소개 정보를 띄우는 UI 변경
- 학생의 자기소개 정보를 띄우는 UI 변경

🔀 :: 학생 정보 페이지 자기소개 UI 변경 및 프로젝트, 수상 Response 추가

---

Projects/Domain/StudentDomain/Interface/Entity/PrizeEntity.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/View/PrizeRowView.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/View/StudentDetailTitleWrapper.swift

🔀 :: 학생 정보 디테일 페이지에 수상 항목 추가

---

Projects/Domain/BaseDomain/Project.swift

- CD를 구축하느라 XCConfig 연결 시스템이 바뀌었는데, BaseDomain이 Shared.xcconfig만 참조한 상태
- BaseDomain이 전용 xcconfig를 가져가도록 변경
- BaseDomain이 전용 xcconfig를 가져가도록 변경

🔀 :: [#255] BaseDomain XCConfig 연결

---

Projects/Feature/FilterFeature/Sources/Scene/FilterView.swift
Projects/Feature/InputPrizeInfoFeature/Sources/Intent/InputPrizeInfoIntent.swift
Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModel.swift
Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModelProtocol.swift
Projects/Feature/InputPrizeInfoFeature/Sources/Scene/InputPrizeInfoView.swift
Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Projects/Feature/InputProjectInfoFeature/Sources/Intent/InputProjectInfoIntent.swift
Projects/Feature/InputProjectInfoFeature/Sources/Model/InputProjectInfoModel.swift
Projects/Feature/InputProjectInfoFeature/Sources/Model/InputProjectInfoModelProtocol.swift
Projects/Feature/InputProjectInfoFeature/Sources/Scene/InputProjectInfoView.swift
Projects/Feature/MyPageFeature/Project.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPagePrizeIntentProtocol.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageProfileIntent.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageProjectIntent.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageModel.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageModelProtocol.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPagePrizeModel.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageProfileModel.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageProjectModel.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPagePrizeView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageProfileView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageProjectView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift

필수요소 검사해서 에러 띄우기
* 마이페이지 project, profile, prize 필수 요소 검사
* input project, prize 필수 요소 검사
이론상 될겁니다. ~~아마도~~

🔀 :: [#252] 필수요소 검사해서 에러 띄우기

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntentProtocol.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageProfileIntent.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageModel.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageModelProtocol.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageProfileView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift

🔀 :: [#269] 정보입력 직접입력 안되는 버그 수정

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Core/DesignSystem/Sources/CameraPicker/CameraPicker.swift

카메라를 이용해 촬영할 때, 권한을 미부여하면 이후에 다시 묻도록 
,

🔀 :: [#284] Camera 권한 확인 추가

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntentProtocol.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageModel.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPageWorkInfoModel.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageProjectView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageSchoolLifeView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageWorkInfoView.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/View/ProjectRowView.swift
Projects/Shared/Validator/Sources/URLValidator.swift

짜잘한 버그 수정
* 이미지 띄우는 방법 처리
* salary 텍스트 버그 수정
* 오류 텍스트들 가운데 정렬 해결

🔀 :: [#290] 짜잘한 버그 수정

---

Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntent.swift

기술스택 글자 수 30자 제한
- TechStackAppendIntent의 Text가 입력될 때 최대 글자 수 validation

🔀 :: [#296] 기술스택 글자 수 30자 제한

---

Projects/App/Sources/Application/DI/AppComponent.swift
Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/InputSchoolLifeInfoFeature/Interface/InputSchoolLifeInfoBuildable.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/DI/InputSchoolLifeInfoComponent.swift

Needle 스크립트를 돌리면 parent compnent로부터 주입을 못받아서 빌드가 실패가 나는 현상이 발견되었어요.
https://github.com/uber/needle/releases/tag/v0.24.0
needle의 최신 릴리즈를 보니 의존성을 내려줄때 internal 접근 제한자는 무시해요.
=> 주입을 위한 프로퍼티는 모두 public 접근 제한자를 붙여주어요.
Needle 최신 버전 변경사항 반영
AppComponent의 register를 위한 의존성은 모두 public 접근 제한자 설정

🔀 :: [#313] Needle에서 parent compnent로부터 주입을 못받는 현상을 해결해요

---

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
Projects/App/Project.swift
Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/InputTeacherInfoFeature/Demo/Resources/LaunchScreen.storyboard
Projects/Feature/InputTeacherInfoFeature/Demo/Sources/AppDelegate.swift
Projects/Feature/InputTeacherInfoFeature/Interface/InputTeacherDelegate.swift
Projects/Feature/InputTeacherInfoFeature/Interface/InputTeacherInfoBuildable.swift
Projects/Feature/InputTeacherInfoFeature/Interface/Interface.swift
Projects/Feature/InputTeacherInfoFeature/Project.swift
Projects/Feature/InputTeacherInfoFeature/Sources/DI/InputTeacherInfoComponent.swift
Projects/Feature/InputTeacherInfoFeature/Sources/Intent/InputTeacherInfoIntent.swift
Projects/Feature/InputTeacherInfoFeature/Sources/Intent/InputTeacherInfoIntentProtocol.swift
Projects/Feature/InputTeacherInfoFeature/Sources/Model/InputTeacherInfoModel.swift
Projects/Feature/InputTeacherInfoFeature/Sources/Model/InputTeacherInfoModelProtocol.swift
Projects/Feature/InputTeacherInfoFeature/Sources/Scene/InputTeacherInfoView.swift
Projects/Feature/InputTeacherInfoFeature/Sources/Source.swift
Projects/Feature/InputTeacherInfoFeature/Tests/InputTeacherInfoFeatureTest.swift

선생님 정보입력 페이지 UI를 추가했습니다.
https://github.com/GSM-MSG/SMS-iOS/assets/105629604/226dafa4-0075-4651-944e-1846032a66b1
현재 선생님 정보입력 페이지는 선생님 계정으로 GAuth로그인을 하고 SMS 회원가입이 안 되어있을 때 띄워지는 View인데요!
그렇다면 제가 생각했을 때는 
1번 : RootFeature에 successToSignin에서 userRoleType에 따라 updateSceneType이 바뀌게 한다.
2번 : SigninDelegate에 학생로그인 선생님로그인으로 나누어서 SigninFeature에서 UseCase 호출을 한다.
2개 정도가 떠올랐는데요! API 명세서를 봤을 땐 1번이 더 맞을 거 같아 고민이 됩니다! 어떻게 하는 게 좋을까요?
나중에 학년, 반 BottomSheet부분은 담임선생님을 선택했을 때 나타나도록 변경됩니다.

🔀 :: [#315] 선생님 정보입력 페이지 UI

---

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
Projects/App/Project.swift
Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Core/DesignSystem/Sources/TextField/SMSTextEditor.swift
Projects/Feature/InputAuthenticationFeature/Demo/Resources/LaunchScreen.storyboard
Projects/Feature/InputAuthenticationFeature/Demo/Sources/AppDelegate.swift
Projects/Feature/InputAuthenticationFeature/Interface/InputAuthenticationBuildable.swift
Projects/Feature/InputAuthenticationFeature/Interface/InputAuthenticationDelegate.swift
Projects/Feature/InputAuthenticationFeature/Project.swift
Projects/Feature/InputAuthenticationFeature/Sources/DI/InputAuthenticationComponent.swift
Projects/Feature/InputAuthenticationFeature/Sources/Intent/InputAuthenticationIntent.swift
Projects/Feature/InputAuthenticationFeature/Sources/Intent/InputAuthenticationProtocol.swift
Projects/Feature/InputAuthenticationFeature/Sources/Model/InputAuthenticationModel.swift
Projects/Feature/InputAuthenticationFeature/Sources/Model/InputAuthenticationModelProtocol.swift
Projects/Feature/InputAuthenticationFeature/Sources/Scene/InputAuthenticationView.swift
Projects/Feature/InputAuthenticationFeature/Sources/Source.swift
Projects/Feature/InputAuthenticationFeature/Tests/InputAuthenticationFeatureTest.swift

인증제 입력 페이지 퍼블리싱
인증제 입력 페이지를 퍼블리싱했습니다
DesignSystem에 SMSTextEditor를 추가했습니다
시뮬레이터에는 네비게이션바에 있는 플러스버튼이 안보여서 영상 찍을 때만 따로 버튼 추가했습니다!! 
https://github.com/GSM-MSG/SMS-iOS/assets/127721819/7d63001a-8229-4845-96d3-2324640a78fc

 🔀 :: [#317] 인증제 입력 페이지 퍼블리싱

---

Projects/Core/DesignSystem/Sources/SegmentedControl/SMSSegmentedControl.swift

Segmented Control 컴포넌트를 추가해요
https://github.com/GSM-MSG/SMS-iOS/assets/74440939/56d23e0a-b6e1-44de-bc65-bb4d01681008
Resolves: #326

🔀  :: [#326] DesignSystem / SMSSegmentedControl

---

Projects/Core/DesignSystem/Sources/SegmentedControl/SMSSegmentedControl.swift

SMSSegmentedControl 외부에서 selected option을 제어 가능하게 변경
Resolves: #336 
- SMSSegmentedControl 파라미터에 selectedOption 추가

🔀  :: [#336] SMSSegmentedControl 외부에서 selected option을 제어 가능하게 변경

---

Projects/Core/DesignSystem/Sources/Dialog/SMSDialog.swift
Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift
Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntentProtocol.swift
Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModelProtocol.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/View/EffectiveDateRadioGroupView.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/View/SelectedEffectiveDateView.swift

기업담당자분들이 학생 개인의 포트폴리오를 열람하기 위해 링크를 생성해야하는 요구사항이 생겼어요.
Resolves: #339 
https://github.com/GSM-MSG/SMS-iOS/assets/105629604/2beb83aa-5036-4bd2-838d-7c2928f39be2

🔀 :: [#339] 포트폴리오 공유 다이얼로그 추가

---

Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift

* complete call 연결
Resolves: #346
complete call 연결

🔀 :: [#346] complete call 연결
