Projects/App/Project.swift
Projects/App/Sources/Application/AppDelegate.swift
Projects/App/Sources/Application/SceneDelegate.swift
Projects/Feature/BaseFeature/Sources/Feature.swift
Projects/Feature/BaseFeature/Sources/MVIContainer.swift

MVI에서 Action을 받고 State를 방출하는 Container 기본 세팅

🔀 :: MVI 세팅

---

Projects/App/Project.swift
Projects/Core/DesignSystem/Project.swift
Projects/Core/DesignSystem/Resources/Neutral.xcassets/Contents.json
Projects/Core/DesignSystem/Resources/Neutral.xcassets/N10.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Neutral.xcassets/N20.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Neutral.xcassets/N30.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Neutral.xcassets/N40.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Neutral.xcassets/N50.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Primary.xcassets/Contents.json
Projects/Core/DesignSystem/Resources/Primary.xcassets/P1.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Primary.xcassets/P2.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Primary.xcassets/P3.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Sub.xcassets/Contents.json
Projects/Core/DesignSystem/Resources/Sub.xcassets/S1.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Sub.xcassets/S2.colorset/Contents.json
Projects/Core/DesignSystem/Resources/Sub.xcassets/S3.colorset/Contents.json
Projects/Core/DesignSystem/Resources/System.xcassets/Black.colorset/Contents.json
Projects/Core/DesignSystem/Resources/System.xcassets/Contents.json
Projects/Core/DesignSystem/Resources/System.xcassets/Error.colorset/Contents.json
Projects/Core/DesignSystem/Resources/System.xcassets/Positive.colorset/Contents.json
Projects/Core/DesignSystem/Resources/System.xcassets/White.colorset/Contents.json
Projects/Core/DesignSystem/Sources/Color/Color+sms.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Neutral.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Primary.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Sub.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+System.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorable.swift
Projects/Core/DesignSystem/Sources/Feature.swift
Projects/Shared/DateUtil/Tests/DateFormatUtilSpec.swift

ColorDesignSystem 제작
ColorDesignSystem 제작

🔀 :: ColorDesignSystem 제작

---

Projects/App/Project.swift
Projects/Core/DesignSystem/Sources/Color/Color+sms.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Neutral.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Primary.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Sub.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+System.swift
Projects/Core/DesignSystem/Sources/Color/SMSColorable.swift

SwiftUI에서 사용하게 변경
UIColor -> Color로 변경

🔀 :: SwiftUI에서 사용하게 변경

---

Projects/App/Support/Info.plist

🔀 :: Appearance Light로 고정

---

.github/workflows/sms-ios-ci.yml
Projects/Shared/DateUtil/Tests/DateFormatUtilSpec.swift

도토리의 IOS CI 스크립트를 참고하여 CI 스크립트를 작성하였습니다.

:green_heart: :: CI 스크립트 작성

---

Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift

🔀 :: SMSTextField 패딩 변경

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/DI/InputMilitaryInfoComponent.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntent.swift
Projects/Feature/InputWorkInfoFeature/Interface/InputWorkDelegate.swift
Projects/Feature/InputWorkInfoFeature/Interface/InputWorkInfoBuildable.swift
Projects/Feature/InputWorkInfoFeature/Sources/DI/InputWorkInfoComponent.swift
Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntentProtocol.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModelProtocol.swift
Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift

🔀 :: 정보 입력 - 근무 조건 페이지 UI

---

Projects/Feature/InputCertificateInfoFeature/Sources/Model/InputCertificateInfoModel.swift
Projects/Feature/InputCertificateInfoFeature/Sources/Scene/InputCertificateInfoView.swift
Projects/Feature/InputLanguageInfoFeature/Sources/Model/InputLanguageInfoModel.swift
Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntentProtocol.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModelProtocol.swift
Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift

근무 조건 페이지 희망 지역 복수입력으로 변경
- 근무 조건 페이지 희망 지역 복수입력으로 변경
- 복수 입력 가능한 페이지들은 모두 스크롤을 가능하도록 변경

🔀 :: 근무 조건 페이지 희망 지역 복수입력으로 변경

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
Projects/Domain/AuthDomain/Interface/Entity/IsAlreadySignUp.swift
Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
Projects/Domain/AuthDomain/Interface/UseCase/LoginUseCase.swift
Projects/Domain/AuthDomain/Sources/DTO/Response/SigninResponseDTO.swift
Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
Projects/Domain/AuthDomain/Sources/UseCase/LoginUseCaseImpl.swift
Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
Projects/Domain/AuthDomain/Testing/UseCase/LoginUseCaseSpy.swift

로그인API에서 학생 정보를 기입한 학생인지 아닌지에 대한 정보를 추가적으로 받습니다
- Signin 부분에서 Bool값을 받아 판별
- IsAlreadySignup typealias를 만들어 Bool을 대신해 표현
- Signin UseCase, Repository, DataSource에 리턴 타입 'IsAlreadySignup' 추가
- typealias를 사용했는데 괜찮을까요..?

🔀 :: 로그인에서 학생 정보를 기입한 학생인지 아닌지에 대한 정보

---

Projects/Shared/ViewUtil/Sources/Extensions/View+hideKeyboard.swift

🔀 :: 화면 클릭 시 키보드 dismiss 처리

---

Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
Projects/Feature/InputInformationFeature/Sources/Scene/View/InputInformationPageWrapView.swift
Projects/Feature/InputProfileInfoFeature/Interface/InputProfileDelegate.swift
Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntent.swift
Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntentProtocol.swift
Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Projects/Feature/InputProfileInfoFeature/Tests/InputProfileInfoFeatureTest.swift
Projects/Shared/Validator/Sources/RegexValidator.swift
Projects/Shared/Validator/Sources/URLValidator.swift
Projects/Shared/ViewUtil/Sources/Extensions/View+buttonWrapper.swift

프로필 정보 입력 검사
- 프로필 정보 입력 검사
- 정보 입력 완료 후 InputInformatino으로 정보 전달

🔀 :: 정보 입력 - 프로필 정보 입력 검사

---

Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
Projects/Feature/InputSchoolLifeInfoFeature/Interface/InputSchoolLifeDelegate.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Intent/InputSchoolLifeInfoIntent.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Intent/InputSchoolLifeInfoIntentProtocol.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModel.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModelProtocol.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Scene/InputSchoolLifeInfoView.swift
Projects/Feature/InputSchoolLifeInfoFeature/Tests/InputSchoolLifeInfoFeatureTest.swift

학교 생활 정보 입력 검사
- 학교 생활 정보 입력 검사
- 정보 입력 완료 후 InforInformation으로 정보 전달

🔀 :: 정보 입력 - 학교 생활 정보 입력 검사

---

Projects/Domain/StudentDomain/Interface/DTO/Request/StudentRequestDTO.swift
Projects/Domain/StudentDomain/Interface/Enums/MilitaryService.swift
Projects/Domain/StudentDomain/Interface/Enums/MilitaryServiceType.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
Projects/Feature/InputMilitaryInfoFeature/Interface/InputMilitaryDelegate.swift
Projects/Feature/InputMilitaryInfoFeature/Project.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntent.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntentProtocol.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/Model/InputMilitaryInfoModel.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/Model/InputMilitaryInfoModelProtocol.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
Projects/Feature/InputMilitaryInfoFeature/Tests/InputMilitaryInfoFeatureTest.swift

🔀 :: 정보 입력 - 병역 정보 검사 및 입력 전달

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
Projects/Feature/InputLanguageInfoFeature/Interface/InputLanguageDelegate.swift
Projects/Feature/InputLanguageInfoFeature/Sources/Intent/InputLanguageInfoIntent.swift
Projects/Feature/InputLanguageInfoFeature/Sources/Intent/InputLanguageInfoIntentProtocol.swift
Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
Projects/Feature/InputLanguageInfoFeature/Tests/InputLanguageInfoFeatureTest.swift

외국어 정보 입력 검사 및 InputInformation에 정보 전달

🔀 :: 정보 입력 - 외국어 정보 입력 검사 및 정보 전달

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift

자기소개 입력 -> 이메일 입력 -> 전공 선택 or 직접 입력 -> 포트폴리오 입력 -> 세부 스택 입력
순으로 FocusField 보내도록 사용성 개선

🔀 :: 프로필 입력 페이지 FocusField 처리

---

Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
Projects/Feature/RootFeature/Sources/Intent/RootIntentProtocol.swift
Projects/Feature/RootFeature/Sources/Scene/RootView.swift
Projects/Feature/SigninFeature/Interface/SigninBuildable.swift
Projects/Feature/SigninFeature/Interface/SigninDelegate.swift
Projects/Feature/SigninFeature/Sources/DI/SigninComponent.swift
Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift

로그인이 성공하면 이미 정보를 입력했는지에 따라 정보 입력 혹은 홈으로 화면을 전환시킵니다.
- SigninDelegate
- RootIntent에서 SigninDelegate 채택 및 준수

🔀 :: 로그인 성공 이후 화면 전환

---

Tuist/Dependencies.swift

3.2.4 버전에 있던 버그가 픽스된 3.2.5 Emdpoint로 버전을 업그레이드합니다
Emdpoint 버전 3.2.4 -> 3.2.5

🔀 :: Emdpoint 버전 업그레이드

---

Projects/Core/DesignSystem/Sources/Loading/SMSLoading.swift

SMSLoading Modifier 
```swift
...
.smsLoading(isLoading: $isLoading)
...
```

🔀 :: SMSLoading Modifier

---

Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
Projects/Feature/RootFeature/Sources/Model/RootModel.swift

InputInformation 생성자에서 delegate 객체를 초기화 해주지 않았음 ㅎ

🔀 :: 정보 기입 완료 후 메인으로 보내기

---

Projects/Feature/RootFeature/Sources/Model/RootModel.swift
Projects/Feature/SigninFeature/Sources/Scene/SigninView.swift

🔀 :: 로그인페이지에 약관 보기 버튼 추가

---

Projects/Domain/StudentDomain/Interface/DTO/Request/FetchStudentListRequestDTO.swift
Projects/Domain/StudentDomain/Interface/Enums/SortType.swift
Projects/Domain/StudentDomain/Sources/Endpoint/StudentEndpoint.swift

🔀 :: 학생 리스트 API 필터 적용

---

Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntent.swift
Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntentProtocol.swift
Projects/Feature/TechStackAppendFeature/Sources/Model/TechStackAppendModel.swift
Projects/Feature/TechStackAppendFeature/Sources/Model/TechStackAppendModelProtocol.swift
Projects/Feature/TechStackAppendFeature/Sources/Scene/TechStackAppendView.swift

TechStackAppend Feature에서 TechStack 선택할 때 토스트 애니메이션을 추가
https://github.com/GSM-MSG/SMS-iOS/assets/74440939/ab6dd5f6-228a-4f4a-9f7b-44778e8f10f7

🔀 :: TechStackAppend Feature에 Toast 애니메이션 추가

---

Projects/Feature/MainFeature/Sources/Model/MainModel.swift
Projects/Feature/MainFeature/Sources/Scene/MainView.swift

게스트 기준에서 학생 리스트를 볼 때 **을 소금으로 변환시켜 보이도록 변경합니다

🔀 :: 게스트 기준 학생 이름을 A** 대신 A소금으로 보이도록 변경

---

Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
Projects/Domain/AuthDomain/Interface/Error/AuthDomainError.swift
Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
Projects/Domain/AuthDomain/Sources/DTO/Response/VerifyIsInputedUserResponseDTO.swift
Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
Projects/Domain/AuthDomain/Sources/UseCase/CheckIsLoggedInUseCaseImpl.swift
Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift

서버로부터 정보입력을 완료했는지 여부를 받고, 이후 리프레시 API요청을 통해 자동 로그인 검증

🔀 :: 자동 로그인 로직 변경

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Domain/AuthDomain/Interface/DI/AuthDomainBuildable.swift
Projects/Domain/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
Projects/Domain/AuthDomain/Interface/UseCase/ClearTokenUseCase.swift
Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
Projects/Domain/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
Projects/Domain/AuthDomain/Sources/UseCase/ClearTokenUseCaseImpl.swift
Projects/Domain/AuthDomain/Testing/DataSource/LocalAuthDataSourceSpy.swift
Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
Projects/Feature/MainFeature/Project.swift
Projects/Feature/MainFeature/Sources/DI/MainComponent.swift
Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
Projects/Feature/MainFeature/Sources/Model/MainModel.swift
Projects/Feature/MainFeature/Sources/Model/MainModelProtocol.swift
Projects/Feature/MainFeature/Sources/Scene/MainView.swift
Projects/Feature/SigninFeature/Sources/DI/SigninComponent.swift
Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift

로그인에서 게스트로 사용하기 눌러서 이동해도 학생으로 취급하던 현상 해결

🔀 :: 게스트 동작 안되던 현상을,, 해결해봅니다!

---

Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift

🔀 :: 게스트 상태일때 유저의 이름이 **로 뜨는 현상

---

Projects/Feature/TechStackAppendFeature/Sources/Scene/TechStackAppendView.swift

🔀 :: 세부 스택 공백 미허용

---

Projects/Core/EventLimiter/Sources/Debouncer.swift
Projects/Core/EventLimiter/Sources/Throttler.swift
Projects/Core/EventLimiter/Tests/DebouncerTest.swift
Projects/Core/EventLimiter/Tests/ThrottlerTests.swift

🔀 :: Throttler 구현

---

Projects/Feature/StudentDetailFeature/Project.swift
Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift
Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntentProtocol.swift
Projects/Feature/StudentDetailFeature/Sources/Model/HWPDocument.swift
Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModelProtocol.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift

드림북 파일 다운로드 시 \(학번이름)-드림북.hwp 으로 변경 및 다운로드 상태 표시
- 드림북 다운로드 상태 추가
- 드림북 다운로드 시 파일 이름 학번 이름으로 변경

🔀 :: 드림북 파일 다운로드 시 \(학번이름)-드림북.hwp 으로 변경

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Core/DesignSystem/Sources/CameraPicker/CameraPicker.swift

- 카메라화면에서 Video를 누르면 앱이 꺼지더군요, 그래서 Video옵션을 죽였습니다

🔀 :: 카메라에서 Video 누를 시 앱 꺼짐 현상

---

Projects/Domain/StudentDomain/Interface/DTO/Request/StudentRequestDTO.swift
Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift

정보 입력 API에 프로젝트와 수상경력을 입력하는 필드를 추가
정보 입력 API에 프로젝트와 수상경력 필드 추가

🔀 :: 정보 입력 API에 프로젝트, 수상경력 추가

---

Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
Projects/Core/DesignSystem/Sources/PageControl/SMSPageControl.swift
Projects/Feature/InputCertificateInfoFeature/Sources/Scene/InputCertificateInfoView.swift
Projects/Feature/InputInformationBaseFeature/Sources/InputInformationPageTitleView.swift
Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
Projects/Feature/InputPrizeInfoFeature/Sources/Scene/InputPrizeInfoView.swift
Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Projects/Feature/InputProjectInfoFeature/Sources/Scene/InputProjectInfoView.swift
Projects/Feature/InputSchoolLifeInfoFeature/Sources/Scene/InputSchoolLifeInfoView.swift
Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift

정보 입력 ... View를 ProgressBar로 수정
* SMSPageControl 수정
* 정보입력 InputInformationPageTitleView 수정

🔀 :: [#225] 정보 입력 ... View를 ProgressBar로 수정

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/App/Support/Info.plist
Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift

🔀 :: 1.1.0 release

---

Projects/Domain/UserDomain/Sources/DTO/Response/FetchMyProfileResponseDTO.swift

MyPage API 수정사항 반영
MyPage API 수정사항 반영
MyPage API의 `profileImg` 를 `profileImgUrl`로 key 이름 변경

🔀 :: [#259] MyPage API 수정사항 반영

---

Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByGuestResponseDTO.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByStudentResponseDTO.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByTeacherResponseDTO.swift

학생 상세 정보 API 수정사항 반영
학생 상세 정보 API 수정사항 반영
- profileImg -> profileImgUrl

🔀 :: [#261] 학생 상세 정보 API 수정사항 반영

---

Projects/App/Project.swift

App모듈의 xcconfig를 App.xcconfig 읽도록 함

🔀 :: [#264] App모듈 xcconfig 설정

---

Projects/App/Support/Info.plist

🔀 :: 1.1.1 release

---

Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift

Military 바텀 시트 버튼 누를 시 내려가게 하기

🔀 :: [#273] Military 바텀 시트 버튼 누를 시 내려가게 하기

---

Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
Projects/Feature/MyPageFeature/Sources/Intent/MyPageWorkInfoIntent.swift

🔀 :: WorkInfo 근무지역 한글자만 입력되는 이슈 해결

---

Projects/Feature/InputPrizeInfoFeature/Sources/Intent/InputPrizeInfoIntent.swift
Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModel.swift
Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModelProtocol.swift
Projects/Feature/MyPageFeature/Sources/Scene/View/ImageMethodPickerView.swift
Projects/Feature/MyPageFeature/Sources/Scene/View/ImageMethodRowView.swift

🔀 :: [#279] 바텀시트 고치기 및 수상 date 옵셔널로 수정

---

Projects/Feature/InputProjectInfoFeature/Sources/Scene/InputProjectInfoView.swift
Projects/Feature/MyPageFeature/Sources/Scene/MyPageProjectView.swift

🔀 :: [#281] 프로젝트 focus 동시에 두개 되던 버그 고치기

---

Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
Projects/Feature/MyPageFeature/Sources/Model/MyPagePrizeModel.swift

🔀 :: [#283] 마이페이지 prize 안 접히는 문제 해결

---

.github/CODEOWNERS

CODEOWNER 내용 수정
CODEOWNER 내용 수정했습니다.
@uuuunseo 
@shwaaaa 
@kimkyumbi 
@hanjaehyeong 
추가

🔀  :: [#306] CODEOWNERS 추가

---

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
Projects/App/Project.swift
Projects/Domain/BaseDomain/Sources/Base/SMSDomain.swift
Projects/Domain/TeacherDomain/Interface/DI/TeacherDomainBuildable.swift
Projects/Domain/TeacherDomain/Interface/DateSource/RemoteTeacherDataSource.swift
Projects/Domain/TeacherDomain/Interface/Error/TeacherDomainError.swift
Projects/Domain/TeacherDomain/Interface/Interface.swift
Projects/Domain/TeacherDomain/Interface/Repository/TeacherRepository.swift
Projects/Domain/TeacherDomain/Interface/UseCase/CommonSignupUseCase.swift
Projects/Domain/TeacherDomain/Interface/UseCase/DeputyPrincipalSignupUseCase.swift
Projects/Domain/TeacherDomain/Interface/UseCase/DirectorSignupUseCase.swift
Projects/Domain/TeacherDomain/Interface/UseCase/HomeRoomSignupUseCase.swift
Projects/Domain/TeacherDomain/Interface/UseCase/PrincipalSignupUseCase.swift
Projects/Domain/TeacherDomain/Project.swift
Projects/Domain/TeacherDomain/Sources/DI/TeacherDomainComponent.swift
Projects/Domain/TeacherDomain/Sources/DataSource/RemoteTeacherDataSourceImpl.swift
Projects/Domain/TeacherDomain/Sources/Endpoint/TeacherEndPoint.swift
Projects/Domain/TeacherDomain/Sources/Repository/TeacherRepositoryImpl.swift
Projects/Domain/TeacherDomain/Sources/Source.swift
Projects/Domain/TeacherDomain/Sources/UseCase/CommonSignupUseCaseImpl.swift
Projects/Domain/TeacherDomain/Sources/UseCase/DeputyPrincipalSignupUseCaseImpl.swift
Projects/Domain/TeacherDomain/Sources/UseCase/DirectorSignupUseCaseImpl.swift
Projects/Domain/TeacherDomain/Sources/UseCase/HomeRoomSignupUseCaseImpl.swift
Projects/Domain/TeacherDomain/Sources/UseCase/PrincipalSignupUseCaseImpl.swift
Projects/Domain/TeacherDomain/Testing/Testing.swift
Projects/Domain/TeacherDomain/Tests/TeacherDomainTest.swift

teacher 도메인 세팅
teacher 도메인을 세팅했어요

🔀 :: [#318] teacher 도메인 세팅

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Feature/InputAuthenticationFeature/Project.swift

🔀 :: [#323] 오류 해결

---

Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Contents.json
Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Xmark.svg

🔀  :: [#328] SMSTextField / xmark 아이콘 변경

---

Projects/Core/DesignSystem/Sources/Chip/SMSChip.swift
Projects/Core/DesignSystem/Sources/Chip/SMSChipButtonStyle.swift

Border Style 제작했습니당
Resolves: #332

🔀 :: [#332] DesignSystem / Chip

---

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
Projects/App/Project.swift
Projects/Feature/GSMAuthenticationFormFeature/Demo/Resources/LaunchScreen.storyboard
Projects/Feature/GSMAuthenticationFormFeature/Demo/Sources/AppDelegate.swift
Projects/Feature/GSMAuthenticationFormFeature/Interface/Interface.swift
Projects/Feature/GSMAuthenticationFormFeature/Project.swift
Projects/Feature/GSMAuthenticationFormFeature/Sources/Source.swift
Projects/Feature/GSMAuthenticationFormFeature/Tests/GSMAuthenticationFormFeatureTest.swift

GSM Authentication Form Feature 추가
Resolves: #334 
- `GSMAuthrnticationFormFeature` 를 추가했어요
- Interface, Implementations, Unit Tests, Demo 모듈을 포함함
- 모듈 추가 후 UI 빌딩할 수 있게 해요

🔀 :: [#334] GSMAuthenticationForm Feature 추가

---

Projects/Domain/StudentDomain/Interface/DI/StudentDomainBuildable.swift
Projects/Domain/StudentDomain/Interface/DTO/Request/CreatePortfolioLinkRequestDTO.swift
Projects/Domain/StudentDomain/Interface/DataSource/RemoteStudentDataSource.swift
Projects/Domain/StudentDomain/Interface/Entity/PortfolioLinkEntity.swift
Projects/Domain/StudentDomain/Interface/Repository/StudentRepository.swift
Projects/Domain/StudentDomain/Interface/UseCase/CreatePortfolioLinkUseCase.swift
Projects/Domain/StudentDomain/Sources/DI/StudentDomainComponent.swift
Projects/Domain/StudentDomain/Sources/DTO/Response/CreatePortfolioLinkResponseDTO.swift
Projects/Domain/StudentDomain/Sources/DataSource/RemoteStudentDataSourceImpl.swift
Projects/Domain/StudentDomain/Sources/Endpoint/StudentEndpoint.swift
Projects/Domain/StudentDomain/Sources/Repository/StudentRepositoryImpl.swift
Projects/Domain/StudentDomain/Sources/UseCase/CreatePortfolioLinkUseCaseImpl.swift
Projects/Domain/StudentDomain/Testing/UseCase/CreatePortfolioLinkUseCaseSpy.swift
Projects/Feature/StudentDetailFeature/Demo/Sources/StudentDetailDemoApp.swift
Projects/Feature/StudentDetailFeature/Sources/DI/StudentDetailComponent.swift
Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift
Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntentProtocol.swift
Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModelProtocol.swift
Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift

학생 링크 공유 기능 추가
Resolves: #343 
학생 링크 공유 기능을 추가했어요
> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!

🔀 :: [#343] 포트폴리오 공유 기능 추가

---

Projects/Feature/GSMAuthenticationFormFeature/Sources/Scene/Components/GSMAuthenticationFileDownloadView.swift

- 파일 다운로드 섹션 Collapse 기능을 제공해요.
Resolves: #349 
- 파일 다운로드 섹션 Collapse 기능을 제공해요.

💄  :: [#349] 파일 다운로드 섹션 Collapse 기능 제공
